# Start with the Ubuntu minumal base image 
FROM ubuntu:20.04 

# Install Nginx
RUN apt-get update && apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/* && \
    echo "Custom HTML Response" > /usr/share/nginx/html/index.html

# Avoid unnecessary files in COPY Statements - to keep the image size small
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose the necessary ports 
EXPOSE 8080 8081

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
