version: '3'
services:
  nginx:
    build:
      context: ./nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: ./tester/Dockerfile
    depends_on:
      - nginx
