version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx_server

  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - nginx
    container_name: nginx_tester
