services:
  nginx:
    build:
      context: ./nginx            # Set context to the nginx folder
      dockerfile: Dockerfile       # Specify Dockerfile within the nginx context
    ports:
      - "8080:8080"
      - "8081:8081"

  # tester:
  #   build:
  #     context: ./tester            # Set context to the tester folder
  #     dockerfile: Dockerfile       # Specify Dockerfile within the tester context
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./result:/result
