version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - nginx
    volumes:
      - ./result:/result
