FROM nginx:alpine #use a lightweight version
RUN apt-get update && apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/* && \
    echo "Custom HTML Response" > /usr/share/nginx/html/index.html

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080 8081

CMD ["nginx", "-g", "daemon off;"]
