name: Docker CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d
          sleep 5  # Wait for services to start

      # Run the test container
      - name: Run tests in tester container
        id: test
        run: |
          docker-compose run --rm tester && echo "succeeded" > result.txt || echo "fail" > result.txt

      # Upload artifact based on test results
      - name: Upload test result artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.test.outputs.result }}
          path: result.txt

      # Tear down Docker Compose
      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down

