name: Build and Test Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d
          sleep 20  # Wait for Nginx to initialize
          
      - name: Run tests and check responses
        id: run-tests
        run: |
          # Check if the tester container logs indicate success
          if docker logs $(docker-compose ps -q tester) | grep "200 OK"; then
            echo "Tests passed"
            echo "status=succeeded" >> $GITHUB_ENV
          else
            echo "Tests failed"
            echo "status=fail" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Create result file
        run: |
          touch /tmp/${{ env.status }}

      - name: Publish Result as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.status }}
          path: /tmp/${{ env.status }}
